"""Alert models for security anomalies"""
import enum
from datetime import datetime
from sqlalchemy import Column, String, Enum, Text, Boolean, ForeignKey, JSON
from sqlalchemy.orm import relationship
import uuid

from .base import Base, TimestampMixin


class AlertType(str, enum.Enum):
    """Types of security alerts"""

    UNUSUAL_INTERNATIONAL_CALLS = "unusual_international_calls"
    AFTER_HOURS_ACTIVITY = "after_hours_activity"
    MASS_DIALING = "mass_dialing"
    SUSPICIOUS_CALL_FORWARDING = "suspicious_call_forwarding"
    UNUSUAL_DESTINATION = "unusual_destination"
    RAPID_SEQUENTIAL_CALLS = "rapid_sequential_calls"
    EXTENSION_COMPROMISE = "extension_compromise"


class AlertSeverity(str, enum.Enum):
    """Alert severity levels"""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class Alert(Base, TimestampMixin):
    """
    Security alert generated by anomaly detection
    """

    __tablename__ = "alerts"

    # Primary Key - Use String for SQLite compatibility
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))

    # Alert Classification
    alert_type = Column(Enum(AlertType), nullable=False, index=True)
    severity = Column(Enum(AlertSeverity), nullable=False, index=True)

    # User/Entity Involved
    user_id = Column(String(255), index=True)
    user_name = Column(String(255))
    extension = Column(String(50))
    location = Column(String(255))

    # Alert Details
    title = Column(String(500), nullable=False)
    description = Column(Text)

    # Detection Metrics
    detection_data = Column(JSON)  # Stores ML/rule outputs

    # Claude AI Analysis
    ai_analysis = Column(Text)  # Natural language explanation from Claude
    ai_confidence = Column(String(20))  # LOW, MEDIUM, HIGH
    recommended_action = Column(Text)

    # Risk Assessment
    fraud_likelihood = Column(String(20))  # LOW, MEDIUM, HIGH
    potential_impact = Column(String(20))  # LOW, MEDIUM, HIGH

    # Status & Resolution
    status = Column(
        String(50), default="open", index=True
    )  # open, investigating, resolved, false_positive
    resolved_at = Column(String(50))
    resolved_by = Column(String(255))
    resolution_notes = Column(Text)

    # Notifications
    notification_sent = Column(Boolean, default=False)
    notification_channels = Column(JSON)  # ["email", "slack", "webex"]

    # Related Data
    related_call_ids = Column(JSON)  # Array of call_ids that triggered alert
    related_journey_ids = Column(JSON)

    def __repr__(self):
        return f"<Alert {self.alert_type.value} - {self.severity.value} - {self.user_name}>"
